spring:
  application:
    name: spring-ai-experiments
  ai:
    ollama:
      base-url: http://localhost:11434
      pull-model-strategy: never
      chat:
        options:
          model: llama3.1:latest
